export default function TestCase() {
  const RecommendationsTest = {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
        genre_ids: [878, 28, 12],
        id: 624860,
        media_type: "movie",
        title: "The Matrix Resurrections",
        original_language: "en",
        original_title: "The Matrix Resurrections",
        overview:
          "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
        popularity: 3120.12,
        poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
        release_date: "2021-12-16",
        video: false,
        vote_average: 6.92,
        vote_count: 2334,
      },
      {
        adult: false,
        backdrop_path: "/9fzNf2QcsHVvdx5g5QUOgAWpADw.jpg",
        genre_ids: [18, 27, 9648],
        id: 516329,
        media_type: "movie",
        title: "Antlers",
        original_language: "en",
        original_title: "Antlers",
        overview:
          "A small-town Oregon teacher and her brother, the local sheriff, discover a young student is harbouring a dangerous secret that could have frightening consequences.",
        popularity: 1201.439,
        poster_path: "/cMch3tiexw3FdOEeZxMWVel61Xg.jpg",
        release_date: "2021-10-28",
        video: false,
        vote_average: 6.4,
        vote_count: 362,
      },
      {
        adult: false,
        backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
        genre_ids: [35, 14, 12],
        id: 425909,
        media_type: "movie",
        title: "Ghostbusters: Afterlife",
        original_language: "en",
        original_title: "Ghostbusters: Afterlife",
        overview:
          "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
        popularity: 4275.13,
        poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
        release_date: "2021-11-11",
        video: false,
        vote_average: 7.724,
        vote_count: 1347,
      },
      {
        adult: false,
        backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
        genre_ids: [16, 35, 10751, 14],
        id: 568124,
        media_type: "movie",
        title: "Encanto",
        original_language: "en",
        original_title: "Encanto",
        overview:
          "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
        popularity: 4960.193,
        poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
        release_date: "2021-11-24",
        video: false,
        vote_average: 7.77,
        vote_count: 3134,
      },
      {
        adult: false,
        backdrop_path: "/nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg",
        genre_ids: [35, 18, 878],
        id: 646380,
        media_type: "movie",
        title: "Don't Look Up",
        original_language: "en",
        original_title: "Don't Look Up",
        overview:
          "Two low-level astronomers must go on a giant media tour to warn humankind of an approaching comet that will destroy planet Earth.",
        popularity: 671.104,
        poster_path: "/th4E1yqsE8DGpAseLiUrI60Hf8V.jpg",
        release_date: "2021-12-07",
        video: false,
        vote_average: 7.271,
        vote_count: 3881,
      },
      {
        adult: false,
        backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
        genre_ids: [28, 12, 878],
        id: 634649,
        media_type: "movie",
        title: "Spider-Man: No Way Home",
        original_language: "en",
        original_title: "Spider-Man: No Way Home",
        overview:
          "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
        popularity: 6211.386,
        poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
        release_date: "2021-12-15",
        video: false,
        vote_average: 8.365,
        vote_count: 4351,
      },
      {
        adult: false,
        backdrop_path: "/1BqX34aJS5J8PefVnQSfQIEPfkl.jpg",
        genre_ids: [80, 28, 53],
        id: 826749,
        media_type: "movie",
        title: "Fortress",
        original_language: "en",
        original_title: "Fortress",
        overview:
          "The story revolves around a top-secret resort for retired U.S. intelligence officers. A group of criminals led by Balzary breach the compound, hellbent on revenge on Robert, forcing the retired officer and his son to save the day.",
        popularity: 1093.262,
        poster_path: "/vQxtoPJVfpHgL7DCg9hQFZKDWJa.jpg",
        release_date: "2021-12-17",
        video: false,
        vote_average: 6.315,
        vote_count: 119,
      },
      {
        adult: false,
        backdrop_path: "/AmLpWYm9R3Ur2FLPgj5CH3wR8wp.jpg",
        genre_ids: [878, 53],
        id: 739413,
        media_type: "movie",
        title: "Mother/Android",
        original_language: "en",
        original_title: "Mother/Android",
        overview:
          "Georgia and her boyfriend Sam go on a treacherous journey to escape their country, which is caught in an unexpected war with artificial intelligence. Days away from the arrival of their first child, the couple must face No Man’s Land—a stronghold of the android uprising—in hopes of reaching safety before giving birth.",
        popularity: 2119.02,
        poster_path: "/rO3nV9d1wzHEWsC7xgwxotjZQpM.jpg",
        release_date: "2021-12-17",
        video: false,
        vote_average: 5.984,
        vote_count: 282,
      },
      {
        adult: false,
        backdrop_path: "/vECdJXyERcp9g8dpK691y4hb6xG.jpg",
        genre_ids: [18, 53],
        id: 821427,
        media_type: "movie",
        title: "The Novice",
        original_language: "en",
        original_title: "The Novice",
        overview:
          "A college freshman joins her university's rowing team and undertakes an obsessive physical and psychological journey to make it to the top varsity boat, no matter the cost.",
        popularity: 11.745,
        poster_path: "/lbawQgnb3xnaJNfTJp5CRC7uAgs.jpg",
        release_date: "2021-12-17",
        video: false,
        vote_average: 6.448,
        vote_count: 29,
      },
      {
        adult: false,
        backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
        genre_ids: [16, 35, 10751, 10402],
        id: 438695,
        media_type: "movie",
        title: "Sing 2",
        original_language: "en",
        original_title: "Sing 2",
        overview:
          "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
        popularity: 5606.735,
        poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
        release_date: "2021-12-01",
        video: false,
        vote_average: 8.319,
        vote_count: 1093,
      },
      {
        adult: false,
        backdrop_path: "/kbOB9DGl8qwhDRcXOmXfmcmadeD.jpg",
        genre_ids: [18, 80],
        id: 645886,
        media_type: "movie",
        title: "The Unforgivable",
        original_language: "en",
        original_title: "The Unforgivable",
        overview:
          "A woman is released from prison after serving a sentence for a violent crime and re-enters a society that refuses to forgive her past.",
        popularity: 245.236,
        poster_path: "/1b3dNFDuE7i05TJlXrIC571yR01.jpg",
        release_date: "2021-11-24",
        video: false,
        vote_average: 7.608,
        vote_count: 1006,
      },
      {
        adult: false,
        backdrop_path: "/ibdmSDwCpDYNdIkGeu7prsMVzYZ.jpg",
        genre_ids: [18, 878],
        id: 765245,
        media_type: "movie",
        title: "Swan Song",
        original_language: "en",
        original_title: "Swan Song",
        overview:
          "In the near future, Cameron Turner is diagnosed with a terminal illness. Presented with an experimental solution to shield his wife and son from grief, he grapples with altering their fate.",
        popularity: 140.429,
        poster_path: "/y0WW5vX58oMEg9aRRTB5QtG1Vyn.jpg",
        release_date: "2021-12-17",
        video: false,
        vote_average: 7.29,
        vote_count: 167,
      },
      {
        adult: false,
        backdrop_path: "/jiFHFWIafrxJ5FGrvyOS0ISgRws.jpg",
        genre_ids: [28, 80, 53, 9648],
        id: 557946,
        media_type: "movie",
        title: "Last Looks",
        original_language: "en",
        original_title: "Last Looks",
        overview:
          "A disgraced ex-cop seeks solace by moving to the woods, but his quiet life comes to an end when a private eye recruits him to investigate the murder of an eccentric TV star's wife.",
        popularity: 29.295,
        poster_path: "/ud0XdA2xAghDR66j3I84DnNlC2g.jpg",
        release_date: "2021-12-02",
        video: false,
        vote_average: 6.3,
        vote_count: 47,
      },
      {
        adult: false,
        backdrop_path: "/g8dafKwLfaueQ5GK0qjKTkRCBAA.jpg",
        genre_ids: [99],
        id: 899082,
        media_type: "movie",
        title: "Harry Potter 20th Anniversary: Return to Hogwarts",
        original_language: "en",
        original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
        overview:
          "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
        popularity: 814.746,
        poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
        release_date: "2022-01-01",
        video: false,
        vote_average: 8.39,
        vote_count: 778,
      },
      {
        adult: false,
        backdrop_path: "/lXGa1MgoqfgmcDSvKSPsueT9n73.jpg",
        genre_ids: [18],
        id: 632617,
        media_type: "movie",
        title: "C'mon C'mon",
        original_language: "en",
        original_title: "C'mon C'mon",
        overview:
          "Johnny and his young nephew forge a tenuous but transformational relationship when they embark on a cross-country trip to see life away from Los Angeles.",
        popularity: 24.963,
        poster_path: "/hROb7nFIM3cnk28J0jk4rFBXGQ9.jpg",
        release_date: "2021-11-19",
        video: false,
        vote_average: 7.682,
        vote_count: 77,
      },
      {
        adult: false,
        backdrop_path: "/6v4JNim6vJQ7JljMxxCANqHDe1n.jpg",
        genre_ids: [28, 27],
        id: 892113,
        media_type: "movie",
        title: "Death Valley",
        original_language: "en",
        original_title: "Death Valley",
        overview:
          "Mercenaries with nothing to lose are hired to rescue a bioengineer imprisoned in a cold war bunker. Upon entering the ominous facility, they find themselves in a fight for their lives when they come under attack from an unknown and deadly creature.",
        popularity: 8.063,
        poster_path: "/3SCV6GqtQ4QFvzxS0YxPNYgdHLk.jpg",
        release_date: "2021-11-18",
        video: false,
        vote_average: 5.083,
        vote_count: 12,
      },
      {
        adult: false,
        backdrop_path: "/6p4yHucexKDgsZmHw6TQXkMIEiO.jpg",
        genre_ids: [28, 18, 37, 12],
        id: 729577,
        media_type: "movie",
        title: "The Last Son",
        original_language: "en",
        original_title: "The Last Son",
        overview:
          "Sam Worthington stars as Isaac LeMay, a murderous outlaw who learns he is cursed by a prophecy: one of his children will kill him. To prevent this, he hunts down each of his estranged children including long-lost son Cal (Colson Baker). With bounty hunters and Sheriff Solomon (Thomas Jane) on his tail, LeMay must find a way to stop his children and end the curse.",
        popularity: 22.477,
        poster_path: "/qV8ntQjXgfEQSzviF73lfgfGxEI.jpg",
        release_date: "2021-12-10",
        video: false,
        vote_average: 6.0,
        vote_count: 31,
      },
      {
        adult: false,
        backdrop_path: "/ezyFE2H7vdFoK3dXK4p4ZUaTukW.jpg",
        genre_ids: [16, 10751, 35],
        id: 823610,
        media_type: "movie",
        title: "Seal Team",
        original_language: "en",
        original_title: "Seal Team",
        overview:
          "After his best friend is killed in a shark attack, Quinn, a lovable yet tenacious seal assembles a SEAL TEAM to fight back against a gang of sharks overtaking the neighborhood. But this merry band of international seals are not at all trained for such a mission. They seek the help of a much more skillful combatant, Claggart, but even his tricks and flips can’t whip these guys into shape. However, with a little bit of ingenuity, intelligence and a lot of heart, our SEAL TEAM may actually be able to bring peace back to their undersea community.",
        popularity: 733.139,
        poster_path: "/yPZ3I27oeSm4zVesgMxXlhW8GDe.jpg",
        release_date: "2021-10-28",
        video: false,
        vote_average: 6.994,
        vote_count: 84,
      },
      {
        adult: false,
        backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
        genre_ids: [878, 28, 12],
        id: 580489,
        media_type: "movie",
        title: "Venom: Let There Be Carnage",
        original_language: "en",
        original_title: "Venom: Let There Be Carnage",
        overview:
          "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
        popularity: 2594.922,
        poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
        release_date: "2021-09-30",
        video: false,
        vote_average: 7.144,
        vote_count: 5904,
      },
      {
        adult: false,
        backdrop_path: "/4wfA61Mi6E8GncUn8ze4w0jz0Za.jpg",
        genre_ids: [18, 36],
        id: 517088,
        media_type: "movie",
        title: "Being the Ricardos",
        original_language: "en",
        original_title: "Being the Ricardos",
        overview:
          "Follows Lucille Ball and Desi Arnaz as they face a crisis that could end their careers and another that could end their marriage.",
        popularity: 103.039,
        poster_path: "/oztBLWdRk5gApYmNdADXvXkLT5m.jpg",
        release_date: "2021-12-10",
        video: false,
        vote_average: 6.624,
        vote_count: 178,
      },
      {
        adult: false,
        backdrop_path: "/mFbS5TwN95BcSEfiztdchLgTQ0v.jpg",
        genre_ids: [18, 36],
        id: 617653,
        media_type: "movie",
        title: "The Last Duel",
        original_language: "en",
        original_title: "The Last Duel",
        overview:
          "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.",
        popularity: 872.971,
        poster_path: "/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
        release_date: "2021-10-13",
        video: false,
        vote_average: 7.56,
        vote_count: 1484,
      },
    ],
    total_pages: 2,
    total_results: 40,
  };

  const VideosTest = {
    id: 624860,
    results: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "The Cast Explains The Matrix",
        key: "OZF7aFzcK4I",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2021-12-24T18:00:16.000Z",
        id: "61c700d566a0d3001cac18fe",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: '"Back To Life"',
        key: "aH6ZzDZglS4",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2021-12-18T02:20:16.000Z",
        id: "61bd618f873f00005f687ce9",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "The Game Awards Clip",
        key: "GlDr6aKBtFg",
        site: "YouTube",
        size: 1080,
        type: "Clip",
        official: true,
        published_at: "2021-12-10T04:01:19.000Z",
        id: "61b2f07d65686e001c35ebab",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer 2",
        key: "nNpvWBuTfrc",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2021-12-06T17:00:29.000Z",
        id: "61ae8487f8aee8001a94e098",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: '"Déjà Vu"',
        key: "IgYs_NDyaLs",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2021-12-01T17:00:09.000Z",
        id: "61a8dda60486380029843221",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "The Matrix Legacy",
        key: "0BZUMD85S7s",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2021-10-07T16:03:22.000Z",
        id: "616d3cf5f92532001d31a206",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer 1",
        key: "9ix7TUGVYIo",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2021-09-09T12:58:11.000Z",
        id: "61383821d64ac2006251a095",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Trailer Teaser",
        key: "wdskyfJtyt8",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2021-09-07T16:00:06.000Z",
        id: "61379432da9ef2002bd3e45d",
      },
    ],
  };

  const MovieDetails = {
    adult: false,
    backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
    belongs_to_collection: {
      id: 2344,
      name: "The Matrix Collection",
      poster_path: "/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg",
      backdrop_path: "/bRm2DEgUiYciDw3myHuYFInD7la.jpg",
    },
    budget: 190000000,
    genres: [
      { id: 878, name: "Science Fiction" },
      { id: 28, name: "Action" },
      { id: 12, name: "Adventure" },
    ],
    homepage: "https://www.whatisthematrix.com",
    id: 624860,
    imdb_id: "tt10838180",
    original_language: "en",
    original_title: "The Matrix Resurrections",
    overview:
      "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
    popularity: 3117.579,
    poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    production_companies: [
      {
        id: 174,
        logo_path: "/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png",
        name: "Warner Bros. Pictures",
        origin_country: "US",
      },
      {
        id: 79,
        logo_path: "/tpFpsqbleCzEE2p5EgvUq6ozfCA.png",
        name: "Village Roadshow Pictures",
        origin_country: "US",
      },
      {
        id: 84764,
        logo_path: null,
        name: "Venus Castina Productions",
        origin_country: "US",
      },
    ],
    production_countries: [
      { iso_3166_1: "US", name: "United States of America" },
    ],
    release_date: "2021-12-16",
    revenue: 148000000,
    runtime: 148,
    spoken_languages: [
      { english_name: "English", iso_639_1: "en", name: "English" },
    ],
    status: "Released",
    tagline: "Return to the source.",
    title: "The Matrix Resurrections",
    video: false,
    vote_average: 6.9,
    vote_count: 2474,
  };
}
