import { atom, selector } from "recoil";
import { IUserDB } from "./interfaces";

export const inputState = atom({
  key: "inputState",
  default: "",
});

export const genreState = atom({
  key: "genre",
  default: {
    id: "27",
    name: "액션",
  },
});

export const movieIDState = atom({
  key: "movieIDState",
  default: 568124,
});

export const movieInfoState = atom({
  key: "movieInfoState",
  default: {
    details: {
      adult: false,
      backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
      belongs_to_collection: {
        id: 2344,
        name: "The Matrix Collection",
        poster_path: "/bV9qTVHTVf0gkW0j7p7M0ILD4pG.jpg",
        backdrop_path: "/bRm2DEgUiYciDw3myHuYFInD7la.jpg",
      },
      budget: 190000000,
      genres: [
        { id: 878, name: "Science Fiction" },
        { id: 28, name: "Action" },
        { id: 12, name: "Adventure" },
      ],
      homepage: "https://www.whatisthematrix.com",
      id: 624860,
      imdb_id: "tt10838180",
      original_language: "en",
      original_title: "The Matrix Resurrections",
      overview:
        "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
      popularity: 3117.579,
      poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
      production_companies: [
        {
          id: 174,
          logo_path: "/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png",
          name: "Warner Bros. Pictures",
          origin_country: "US",
        },
        {
          id: 79,
          logo_path: "/tpFpsqbleCzEE2p5EgvUq6ozfCA.png",
          name: "Village Roadshow Pictures",
          origin_country: "US",
        },
        {
          id: 84764,
          logo_path: null,
          name: "Venus Castina Productions",
          origin_country: "US",
        },
      ],
      production_countries: [
        { iso_3166_1: "US", name: "United States of America" },
      ],
      release_date: "2021-12-16",
      revenue: 148000000,
      runtime: 148,
      spoken_languages: [
        { english_name: "English", iso_639_1: "en", name: "English" },
      ],
      status: "Released",
      tagline: "Return to the source.",
      title: "The Matrix Resurrections",
      video: false,
      vote_average: 6.9,
      vote_count: 2474,
    },
    cast: [
      {
        adult: false,
        gender: 2,
        id: 6384,
        known_for_department: "Acting",
        name: "Keanu Reeves",
        original_name: "Keanu Reeves",
        popularity: 60.676,
        profile_path: "/rRdru6REr9i3WIHv2mntpcgxnoY.jpg",
        cast_id: 9,
        character: "Thomas A. Anderson / Neo",
        credit_id: "5d5c58dbc4904800167c7da0",
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 530,
        known_for_department: "Acting",
        name: "Carrie-Anne Moss",
        original_name: "Carrie-Anne Moss",
        popularity: 25.763,
        profile_path: "/xD4jTA3KmVp5Rq3aHcymL9DUGjD.jpg",
        cast_id: 10,
        character: "Tiffany / Trinity",
        credit_id: "5d5c58faa3d02700140ab057",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 1639847,
        known_for_department: "Acting",
        name: "Yahya Abdul-Mateen II",
        original_name: "Yahya Abdul-Mateen II",
        popularity: 13.637,
        profile_path: "/aBDebGZs2pAucyaK4EhHVJGm0Xu.jpg",
        cast_id: 17,
        character: "Morpheus / Agent Smith",
        credit_id: "5d9dffe37f0540001cab4c29",
        order: 2,
      },
      {
        adult: false,
        gender: 1,
        id: 1202689,
        known_for_department: "Acting",
        name: "Jessica Henwick",
        original_name: "Jessica Henwick",
        popularity: 30.173,
        profile_path: "/hRrEqDIWlov1FvYRmBN2vLaAxyl.jpg",
        cast_id: 24,
        character: "Bugs",
        credit_id: "5da7af12944a570019242acb",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 221611,
        known_for_department: "Acting",
        name: "Jonathan Groff",
        original_name: "Jonathan Groff",
        popularity: 12.853,
        profile_path: "/3kmnYKAzSc3Lp7iK5pcj97Hx9Cm.jpg",
        cast_id: 25,
        character: "Smith",
        credit_id: "5deeaf0adc86470019c62610",
        order: 4,
      },
      {
        adult: false,
        gender: 2,
        id: 41686,
        known_for_department: "Acting",
        name: "Neil Patrick Harris",
        original_name: "Neil Patrick Harris",
        popularity: 13.371,
        profile_path: "/qZwbo23uaJU87NxE5RubbeeLTYh.jpg",
        cast_id: 18,
        character: "The Analyst",
        credit_id: "5da63403944a5700132171ad",
        order: 5,
      },
      {
        adult: false,
        gender: 1,
        id: 77234,
        known_for_department: "Acting",
        name: "Priyanka Chopra Jonas",
        original_name: "Priyanka Chopra Jonas",
        popularity: 23.397,
        profile_path: "/x3bxfUPnZY8oSHuAhy8PqAlN5Hn.jpg",
        cast_id: 28,
        character: "Sati",
        credit_id: "5e30e80d98f1f1000fff24ee",
        order: 6,
      },
      {
        adult: false,
        gender: 1,
        id: 6886,
        known_for_department: "Acting",
        name: "Christina Ricci",
        original_name: "Christina Ricci",
        popularity: 20.565,
        profile_path: "/dzB58d6fNrTEi7nBAU1tySJc2at.jpg",
        cast_id: 38,
        character: "Gwyn de Vere",
        credit_id: "60bbd4552dc44e007931d47c",
        order: 7,
      },
      {
        adult: false,
        gender: 1,
        id: 9575,
        known_for_department: "Acting",
        name: "Jada Pinkett Smith",
        original_name: "Jada Pinkett Smith",
        popularity: 21.357,
        profile_path: "/vt1Z1Fsu7gjp4L0OHey9Aa79lWj.jpg",
        cast_id: 23,
        character: "Niobe",
        credit_id: "5da668e3a24232001277dd0b",
        order: 8,
      },
      {
        adult: false,
        gender: 1,
        id: 44793,
        known_for_department: "Acting",
        name: "Telma Hopkins",
        original_name: "Telma Hopkins",
        popularity: 5.862,
        profile_path: "/9uxf7rULOwEcIDV9JLFpy44L1hB.jpg",
        cast_id: 42,
        character: "Freya",
        credit_id: "60ef3c9a5aba32002c41509e",
        order: 9,
      },
      {
        adult: false,
        gender: 2,
        id: 40644,
        known_for_department: "Directing",
        name: "Chad Stahelski",
        original_name: "Chad Stahelski",
        popularity: 8.905,
        profile_path: "/mRe5HlnsJ3rNqcmAhZrCXFZvhIa.jpg",
        cast_id: 142,
        character: "Chad",
        credit_id: "61bb1a6944a424008942e376",
        order: 10,
      },
      {
        adult: false,
        gender: 2,
        id: 2192,
        known_for_department: "Acting",
        name: "Lambert Wilson",
        original_name: "Lambert Wilson",
        popularity: 15.454,
        profile_path: "/5Fx2vg8Qux0LcOFLAGJK6VzET.jpg",
        cast_id: 31,
        character: "The Merovingian",
        credit_id: "5e599b2055c92600154d2b65",
        order: 11,
      },
      {
        adult: false,
        gender: 2,
        id: 22541,
        known_for_department: "Acting",
        name: "Brian J. Smith",
        original_name: "Brian J. Smith",
        popularity: 8.24,
        profile_path: "/tlGXu58XWQXS0404GeioIPme0S.jpg",
        cast_id: 30,
        character: "Berg",
        credit_id: "5e4f29fb9b861600136b5453",
        order: 12,
      },
      {
        adult: false,
        gender: 2,
        id: 1726859,
        known_for_department: "Acting",
        name: "Toby Onwumere",
        original_name: "Toby Onwumere",
        popularity: 3.041,
        profile_path: "/aRTYb7RWQczm5aAkvQm41yw9LN1.jpg",
        cast_id: 26,
        character: "Sequoia",
        credit_id: "5df02fcbeda4b7001803bc0b",
        order: 13,
      },
      {
        adult: false,
        gender: 2,
        id: 38773,
        known_for_department: "Acting",
        name: "Max Riemelt",
        original_name: "Max Riemelt",
        popularity: 13.453,
        profile_path: "/y3w5MgRPOD9M1gsBcbmylNAOi4F.jpg",
        cast_id: 33,
        character: "Sheperd",
        credit_id: "5f058b1d0c27100038824409",
        order: 14,
      },
      {
        adult: false,
        gender: 1,
        id: 970672,
        known_for_department: "Acting",
        name: "Eréndira Ibarra",
        original_name: "Eréndira Ibarra",
        popularity: 11.537,
        profile_path: "/xLEov1eKfOsdtDtFgWUYRW1TeSQ.jpg",
        cast_id: 27,
        character: "Lexy",
        credit_id: "5e22607f2811a10015a2e593",
        order: 15,
      },
      {
        adult: false,
        gender: 2,
        id: 77912,
        known_for_department: "Acting",
        name: "Andrew Lewis Caldwell",
        original_name: "Andrew Lewis Caldwell",
        popularity: 6.633,
        profile_path: "/2g33J4GnUzhCU3GYSswPAh06j9l.jpg",
        cast_id: 29,
        character: "Jude",
        credit_id: "5e3a1f930c27100018755c75",
        order: 16,
      },
      {
        adult: false,
        gender: 2,
        id: 124698,
        known_for_department: "Acting",
        name: "Joshua Grothe",
        original_name: "Joshua Grothe",
        popularity: 14.452,
        profile_path: "/w2PtiAkorYBR3DDaMLajYdb52jB.jpg",
        cast_id: 141,
        character: "FunktIøn",
        credit_id: "61bb19475ad76b0041cdec5b",
        order: 17,
      },
      {
        adult: false,
        gender: 2,
        id: 1069833,
        known_for_department: "Acting",
        name: "Michael X. Sommers",
        original_name: "Michael X. Sommers",
        popularity: 1.803,
        profile_path: "/iL8kK9HoDQ8EZM6TD5eCXng5INM.jpg",
        cast_id: 145,
        character: "Skroce",
        credit_id: "61c8e1e06476540061d7d815",
        order: 18,
      },
      {
        adult: false,
        gender: 2,
        id: 2485018,
        known_for_department: "Acting",
        name: "L. Trey Wilson",
        original_name: "L. Trey Wilson",
        popularity: 0.6,
        profile_path: "/8ZLvEwGJ07uwEGzQi9Ocb4S8Ge5.jpg",
        cast_id: 181,
        character: "Hanno",
        credit_id: "61dd3fdbe24b93008d46f64a",
        order: 19,
      },
      {
        adult: false,
        gender: 0,
        id: 1811913,
        known_for_department: "Acting",
        name: "Mumbi Maina",
        original_name: "Mumbi Maina",
        popularity: 1.206,
        profile_path: "/8mb70XITC2XNo1n1ogGysJjOs72.jpg",
        cast_id: 147,
        character: "Ellster",
        credit_id: "61c8e23a7a1bd6001d4528f1",
        order: 20,
      },
      {
        adult: false,
        gender: 2,
        id: 28432,
        known_for_department: "Acting",
        name: "Max Mauff",
        original_name: "Max Mauff",
        popularity: 7.615,
        profile_path: "/iLbPfx8jKCWKxYkh27yVgJTmHQB.jpg",
        cast_id: 146,
        character: "Quillion",
        credit_id: "61c8e20433ad8f0099304564",
        order: 21,
      },
      {
        adult: false,
        gender: 2,
        id: 85574,
        known_for_department: "Acting",
        name: "Purab Kohli",
        original_name: "Purab Kohli",
        popularity: 2.844,
        profile_path: "/86rSTyRxb63UwmTrJxwjhwfHCbT.jpg",
        cast_id: 182,
        character: "Zen",
        credit_id: "61dd4031945c2000679a9ebe",
        order: 22,
      },
      {
        adult: false,
        gender: 1,
        id: 1182929,
        known_for_department: "Acting",
        name: "Freema Agyeman",
        original_name: "Freema Agyeman",
        popularity: 15.023,
        profile_path: "/qL741lSB4GJIzBRCMz2xzrO7C45.jpg",
        cast_id: 143,
        character: "Astra",
        credit_id: "61c3b23decaef500429f25b2",
        order: 23,
      },
      {
        adult: false,
        gender: 1,
        id: 1632337,
        known_for_department: "Acting",
        name: "Sabrina Strehl",
        original_name: "Sabrina Strehl",
        popularity: 1.4,
        profile_path: "/uCCrra2y1jeVO8kBoF1y0WiFI4X.jpg",
        cast_id: 183,
        character: "Fiona",
        credit_id: "61dd40be68b1ea0066936bfb",
        order: 24,
      },
      {
        adult: false,
        gender: 2,
        id: 1626685,
        known_for_department: "Acting",
        name: "Andrew Rothney",
        original_name: "Andrew Rothney",
        popularity: 5.321,
        profile_path: "/i53QqYktqD2OsteTRaIIW8gUQOK.jpg",
        cast_id: 144,
        character: "Scott",
        credit_id: "61c6f24f37b3a9004dab6cd2",
        order: 25,
      },
      {
        adult: false,
        gender: 2,
        id: 3172012,
        known_for_department: "Acting",
        name: "Cooper Rivers",
        original_name: "Cooper Rivers",
        popularity: 0.6,
        profile_path: "/bzjV2AQPVRPadL2ovIHzoppIQcn.jpg",
        cast_id: 184,
        character: "GJ",
        credit_id: "61dd4114b0040a0041e9de82",
        order: 26,
      },
      {
        adult: false,
        gender: 1,
        id: 3377659,
        known_for_department: "Acting",
        name: "Esther Silex",
        original_name: "Esther Silex",
        popularity: 0.6,
        profile_path: "/xXrltLswZ0idBWgxO52nzInpHRf.jpg",
        cast_id: 185,
        character: "Brainstormer #1",
        credit_id: "61dd423db0040a008e8d5548",
        order: 27,
      },
      {
        adult: false,
        gender: 2,
        id: 3377660,
        known_for_department: "Acting",
        name: "Frank Isom",
        original_name: "Frank Isom",
        popularity: 0.6,
        profile_path: null,
        cast_id: 186,
        character: "Brainstormer #2",
        credit_id: "61dd42541d6c5f004351e7cd",
        order: 28,
      },
      {
        adult: false,
        gender: 2,
        id: 2258037,
        known_for_department: "Acting",
        name: "Leo Sheng",
        original_name: "Leo Sheng",
        popularity: 3.188,
        profile_path: "/nf1ts5rOdxPXfLC6WnHeFN3RB9l.jpg",
        cast_id: 187,
        character: "Bobbi",
        credit_id: "61dd427bb042280041d3f5a8",
        order: 29,
      },
      {
        adult: false,
        gender: 2,
        id: 105108,
        known_for_department: "Visual Effects",
        name: "John Gaeta",
        original_name: "John Gaeta",
        popularity: 0.6,
        profile_path: "/kUzIrTvPr8g4vbVXxDd36IgfuGR.jpg",
        cast_id: 188,
        character: "Deus Machina Employee #1",
        credit_id: "61dd435e5c071b0066e9bbe0",
        order: 30,
      },
      {
        adult: false,
        gender: 2,
        id: 2487737,
        known_for_department: "Acting",
        name: "Donald Mustard",
        original_name: "Donald Mustard",
        popularity: 0.6,
        profile_path: "/1SV4UWcfPq3g3Gidt0apg8E2Gl8.jpg",
        cast_id: 189,
        character: "Deus Machina Employee #2",
        credit_id: "61dd43706743fa001db048f1",
        order: 31,
      },
      {
        adult: false,
        gender: 2,
        id: 1751470,
        known_for_department: "Crew",
        name: "Kim Libreri",
        original_name: "Kim Libreri",
        popularity: 0.61,
        profile_path: "/3DtK9wxMNSY0rvtpqld3nfCeoD7.jpg",
        cast_id: 203,
        character: "Deux Machina Employee #3",
        credit_id: "61dd5376cb3084001dfa8425",
        order: 32,
      },
      {
        adult: false,
        gender: 0,
        id: 1058072,
        known_for_department: "Acting",
        name: "Joe Mazza",
        original_name: "Joe Mazza",
        popularity: 1.632,
        profile_path: "/p9iZdTBca6EZyhR4poXAEDPIUhx.jpg",
        cast_id: 191,
        character: "Cop",
        credit_id: "61dd43f66743fa001db04982",
        order: 33,
      },
      {
        adult: false,
        gender: 2,
        id: 1634010,
        known_for_department: "Acting",
        name: "Julian Grey",
        original_name: "Julian Grey",
        popularity: 5.603,
        profile_path: "/zX57GXBu9v75IWupH9Cp9Ju7wMr.jpg",
        cast_id: 192,
        character: "Brandon",
        credit_id: "61dd449eb0040a0041e9e226",
        order: 34,
      },
      {
        adult: false,
        gender: 2,
        id: 3377669,
        known_for_department: "Acting",
        name: "Gaige Chaturantabut",
        original_name: "Gaige Chaturantabut",
        popularity: 0.84,
        profile_path: "/bsSijdm45ZqV3MrDtLv6VbxQaJ9.jpg",
        cast_id: 193,
        character: "Donnie",
        credit_id: "61dd44b06743fa001db04a27",
        order: 35,
      },
      {
        adult: false,
        gender: 2,
        id: 579330,
        known_for_department: "Acting",
        name: "Tiger Hu Chen",
        original_name: "Tiger Hu Chen",
        popularity: 3.382,
        profile_path: "/ezZ55weUDy7xX02DjV0wwmwyWNl.jpg",
        cast_id: 82,
        character: "M.O.T.C.",
        credit_id: "61485dbe511d090062836845",
        order: 36,
      },
      {
        adult: false,
        gender: 2,
        id: 3708,
        known_for_department: "Crew",
        name: "Volkhart Buff",
        original_name: "Volkhart Buff",
        popularity: 1.458,
        profile_path: "/42DIfmkfF40PAzVxoV8wj1w3x0l.jpg",
        cast_id: 194,
        character: "Kush",
        credit_id: "61dd4508945c2000679aa40a",
        order: 37,
      },
      {
        adult: false,
        gender: 2,
        id: 2224841,
        known_for_department: "Crew",
        name: "Amadei Weiland",
        original_name: "Amadei Weiland",
        popularity: 2.706,
        profile_path: "/rTcefSlxINKaEzlO1GqF2O3wA5X.jpg",
        cast_id: 140,
        character: "Agent White",
        credit_id: "61bb18ab945d36008b5ea76e",
        order: 38,
      },
      {
        adult: false,
        gender: 2,
        id: 1492293,
        known_for_department: "Acting",
        name: "Stephen Dunlevy",
        original_name: "Stephen Dunlevy",
        popularity: 5.503,
        profile_path: "/e0HDyS2xosZ7ByWFBfRoaw07tE5.jpg",
        cast_id: 76,
        character: "Agent Jones",
        credit_id: "613a0728678259008d8006d7",
        order: 39,
      },
      {
        adult: false,
        gender: 1,
        id: 83218,
        known_for_department: "Acting",
        name: "Ellen Hollman",
        original_name: "Ellen Hollman",
        popularity: 10.557,
        profile_path: "/lQLbdJl77YHlGeHIenwTQky8GYN.jpg",
        cast_id: 34,
        character: "Echo",
        credit_id: "5f058b7220af770035e79bd3",
        order: 40,
      },
      {
        adult: false,
        gender: 2,
        id: 95716,
        known_for_department: "Acting",
        name: "Ian Pirie",
        original_name: "Ian Pirie",
        popularity: 3.215,
        profile_path: "/63VIC2jPUgrhSLvwAcbn3NeCFF5.jpg",
        cast_id: 44,
        character: "Lieutenant",
        credit_id: "60ef3e06d18fb9004403efc3",
        order: 41,
      },
      {
        adult: false,
        gender: 2,
        id: 40696,
        known_for_department: "Acting",
        name: "Nicolas de Pruyssenaere",
        original_name: "Nicolas de Pruyssenaere",
        popularity: 2.698,
        profile_path: "/oLQ8FbKjLK7W9HI7YBRtGWJFKHs.jpg",
        cast_id: 195,
        character: "Lead SWAT",
        credit_id: "61dd45626743fa00430c9e06",
        order: 42,
      },
      {
        adult: false,
        gender: 0,
        id: 1827474,
        known_for_department: "Acting",
        name: "Felix Quinton",
        original_name: "Felix Quinton",
        popularity: 0.696,
        profile_path: "/YvcOMuk0cF6ZG92TPGOswmNDA.jpg",
        cast_id: 196,
        character: "SWAT",
        credit_id: "61dd457007291c009b37f52e",
        order: 43,
      },
      {
        adult: false,
        gender: 2,
        id: 3377674,
        known_for_department: "Acting",
        name: "Aaron Pina",
        original_name: "Aaron Pina",
        popularity: 0.6,
        profile_path: "/1znbT7yt4fFQU6L9z87xmNXWodQ.jpg",
        cast_id: 197,
        character: "FBI",
        credit_id: "61dd463568b1ea00195a43c7",
        order: 44,
      },
      {
        adult: false,
        gender: 1,
        id: 3377675,
        known_for_department: "Acting",
        name: "Dani Swan",
        original_name: "Dani Swan",
        popularity: 0.6,
        profile_path: "/cLXsRMKeN5TGwS46B0rBYJf0rIR.jpg",
        cast_id: 198,
        character: "Woman in Red",
        credit_id: "61dd465f6743fa00430c9f5d",
        order: 45,
      },
      {
        adult: false,
        gender: 1,
        id: 3377676,
        known_for_department: "Acting",
        name: "London Breed",
        original_name: "London Breed",
        popularity: 0.6,
        profile_path: "/m75tCSffRZUeHEgMuulLQOTNZ7w.jpg",
        cast_id: 199,
        character: "Calliope",
        credit_id: "61dd46796743fa001db04b95",
        order: 46,
      },
      {
        adult: false,
        gender: 2,
        id: 159291,
        known_for_department: "Acting",
        name: "Steven Roy",
        original_name: "Steven Roy",
        popularity: 1.016,
        profile_path: "/anqHImdLuP74psvkVBR2bhf4jBY.jpg",
        cast_id: 172,
        character: "Thomas's Reflection",
        credit_id: "61d5eea8497560001c12c20b",
        order: 47,
      },
      {
        adult: false,
        gender: 1,
        id: 155293,
        known_for_department: "Acting",
        name: "Mercy Malick",
        original_name: "Mercy Malick",
        popularity: 2.565,
        profile_path: "/tkQoT9k3F3k0RNCQSTSii4bvb3U.jpg",
        cast_id: 204,
        character: "Wife",
        credit_id: "61dd63eb0b5fd600674b6307",
        order: 48,
      },
      {
        adult: false,
        gender: 2,
        id: 3377679,
        known_for_department: "Acting",
        name: "Juval Dieziger",
        original_name: "Juval Dieziger",
        popularity: 0.6,
        profile_path: "/cv5pGBzKDNg3i97xBOMyXb8l8nt.jpg",
        cast_id: 201,
        character: "Utrix Driver",
        credit_id: "61dd477e68b1ea00669373f0",
        order: 49,
      },
      {
        adult: false,
        gender: 2,
        id: 11266,
        known_for_department: "Directing",
        name: "James McTeigue",
        original_name: "James McTeigue",
        popularity: 6.775,
        profile_path: "/8aUklN9PpswTG8DnhVAY92koRMC.jpg",
        cast_id: 202,
        character: "Innocuous Man",
        credit_id: "61dd479dcb30840098cef7ed",
        order: 50,
      },
      {
        adult: false,
        gender: 1,
        id: 1769783,
        known_for_department: "Editing",
        name: "Sarah McTeigue",
        original_name: "Sarah McTeigue",
        popularity: 0.6,
        profile_path: "/2WCq8FcEMC48ahKC02MDani14VP.jpg",
        cast_id: 173,
        character: "Tiffany's Reflection",
        credit_id: "61d5eee131644b00663396f9",
        order: 51,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 1071,
        known_for_department: "Directing",
        name: "Tom Tykwer",
        original_name: "Tom Tykwer",
        popularity: 12.47,
        profile_path: "/9jGSRfOnJTt8xvHtajWl4ZHRV0r.jpg",
        credit_id: "61380b98e93e95002bc15f63",
        department: "Sound",
        job: "Original Music Composer",
      },
      {
        adult: false,
        gender: 2,
        id: 1075,
        known_for_department: "Sound",
        name: "Johnny Klimek",
        original_name: "Johnny Klimek",
        popularity: 1.4,
        profile_path: null,
        credit_id: "61380affb7abb5006237860b",
        department: "Sound",
        job: "Original Music Composer",
      },
      {
        adult: false,
        gender: 2,
        id: 1296,
        known_for_department: "Production",
        name: "Bruce Berman",
        original_name: "Bruce Berman",
        popularity: 1.339,
        profile_path: null,
        credit_id: "6138095df29d6600600c5acf",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 2483,
        known_for_department: "Camera",
        name: "John Toll",
        original_name: "John Toll",
        popularity: 5.894,
        profile_path: "/cfL9A6tC7L5Ps5fq1o3WpVKGMb1.jpg",
        credit_id: "601be5ca81a7fc0041015677",
        department: "Camera",
        job: "Director of Photography",
      },
      {
        adult: false,
        gender: 0,
        id: 8673,
        known_for_department: "Camera",
        name: "Daniele Massaccesi",
        original_name: "Daniele Massaccesi",
        popularity: 5.094,
        profile_path: null,
        credit_id: "6138097c5f6c49002c55b724",
        department: "Camera",
        job: "Director of Photography",
      },
      {
        adult: false,
        gender: 0,
        id: 8673,
        known_for_department: "Camera",
        name: "Daniele Massaccesi",
        original_name: "Daniele Massaccesi",
        popularity: 5.094,
        profile_path: null,
        credit_id: "61c9fd70ecaef500679f117e",
        department: "Camera",
        job: "Steadicam Operator",
      },
      {
        adult: false,
        gender: 2,
        id: 8528,
        known_for_department: "Production",
        name: "Grant Hill",
        original_name: "Grant Hill",
        popularity: 5.624,
        profile_path: "/5rg31yzhZoExI8om31igSMpXx1l.jpg",
        credit_id: "5d5c58aec4904800147c7ba8",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 9339,
        known_for_department: "Writing",
        name: "Lilly Wachowski",
        original_name: "Lilly Wachowski",
        popularity: 9.767,
        profile_path: "/afRagUzIMpmaA3EyKtfsY5xA9TK.jpg",
        credit_id: "5d5c583ea3d02700130aae29",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 1,
        id: 9340,
        known_for_department: "Writing",
        name: "Lana Wachowski",
        original_name: "Lana Wachowski",
        popularity: 28.7,
        profile_path: "/5KNV7YBSPTBUAIXGfIcPmbhho9w.jpg",
        credit_id: "5d5c5827a3d02700170aae23",
        department: "Directing",
        job: "Director",
      },
      {
        adult: false,
        gender: 1,
        id: 9340,
        known_for_department: "Writing",
        name: "Lana Wachowski",
        original_name: "Lana Wachowski",
        popularity: 28.7,
        profile_path: "/5KNV7YBSPTBUAIXGfIcPmbhho9w.jpg",
        credit_id: "5d5c58946743fa00116ed5e6",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 9340,
        known_for_department: "Writing",
        name: "Lana Wachowski",
        original_name: "Lana Wachowski",
        popularity: 28.7,
        profile_path: "/5KNV7YBSPTBUAIXGfIcPmbhho9w.jpg",
        credit_id: "613808b4e93e950065edc368",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 1,
        id: 9340,
        known_for_department: "Writing",
        name: "Lana Wachowski",
        original_name: "Lana Wachowski",
        popularity: 28.7,
        profile_path: "/5KNV7YBSPTBUAIXGfIcPmbhho9w.jpg",
        credit_id: "61eb8642cd20465309653255",
        department: "Writing",
        job: "Writer",
      },
      {
        adult: false,
        gender: 2,
        id: 9344,
        known_for_department: "Art",
        name: "Hugh Bateup",
        original_name: "Hugh Bateup",
        popularity: 2.823,
        profile_path: null,
        credit_id: "6138098ca217c000890f6fcb",
        department: "Art",
        job: "Production Design",
      },
      {
        adult: false,
        gender: 1,
        id: 9346,
        known_for_department: "Art",
        name: "Lisa Brennan",
        original_name: "Lisa Brennan",
        popularity: 0.85,
        profile_path: null,
        credit_id: "617c52513e2ec800635f8a4a",
        department: "Art",
        job: "Set Decoration",
      },
      {
        adult: false,
        gender: 2,
        id: 9349,
        known_for_department: "Sound",
        name: "Dane A. Davis",
        original_name: "Dane A. Davis",
        popularity: 1.96,
        profile_path: "/16RaENd5PxeXs6XE4yrnCPjg4Gz.jpg",
        credit_id: "60f4bb3dbefb09005cf01325",
        department: "Sound",
        job: "Sound Designer",
      },
      {
        adult: false,
        gender: 2,
        id: 9349,
        known_for_department: "Sound",
        name: "Dane A. Davis",
        original_name: "Dane A. Davis",
        popularity: 1.96,
        profile_path: "/16RaENd5PxeXs6XE4yrnCPjg4Gz.jpg",
        credit_id: "60f4bb48da9ef2002dd60423",
        department: "Sound",
        job: "Supervising Sound Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 11266,
        known_for_department: "Directing",
        name: "James McTeigue",
        original_name: "James McTeigue",
        popularity: 6.775,
        profile_path: "/8aUklN9PpswTG8DnhVAY92koRMC.jpg",
        credit_id: "613808e5da9ef2006614509d",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 10903,
        known_for_department: "Production",
        name: "Henning Molfenter",
        original_name: "Henning Molfenter",
        popularity: 1.4,
        profile_path: null,
        credit_id: "61eb89a6848eb900698ee41a",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 10905,
        known_for_department: "Production",
        name: "Charlie Woebcken",
        original_name: "Charlie Woebcken",
        popularity: 1.919,
        profile_path: null,
        credit_id: "61eb89b2976e48011fb4e669",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 11270,
        known_for_department: "Art",
        name: "Peter Walpole",
        original_name: "Peter Walpole",
        popularity: 0.6,
        profile_path: null,
        credit_id: "613809997a1bd6002cfa0bec",
        department: "Art",
        job: "Production Design",
      },
      {
        adult: false,
        gender: 2,
        id: 12785,
        known_for_department: "Directing",
        name: "Terry Needham",
        original_name: "Terry Needham",
        popularity: 2.725,
        profile_path: null,
        credit_id: "6138090d51c01f0025f54058",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 40751,
        known_for_department: "Art",
        name: "Stephan O. Gessler",
        original_name: "Stephan O. Gessler",
        popularity: 0.84,
        profile_path: null,
        credit_id: "617c51ee3876510044a11b0d",
        department: "Art",
        job: "Supervising Art Director",
      },
      {
        adult: false,
        gender: 0,
        id: 40862,
        known_for_department: "Production",
        name: "Miki Emmrich",
        original_name: "Miki Emmrich",
        popularity: 0.694,
        profile_path: null,
        credit_id: "61eb890f5f622b00ba6891c7",
        department: "Production",
        job: "Unit Production Manager",
      },
      {
        adult: false,
        gender: 0,
        id: 40862,
        known_for_department: "Production",
        name: "Miki Emmrich",
        original_name: "Miki Emmrich",
        popularity: 0.694,
        profile_path: null,
        credit_id: "61eb89e55f622b00ba68938c",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 11606,
        known_for_department: "Sound",
        name: "Matthias Lempert",
        original_name: "Matthias Lempert",
        popularity: 1.4,
        profile_path: null,
        credit_id: "617c5459d6dbba0066ca48c6",
        department: "Sound",
        job: "Sound Re-Recording Mixer",
      },
      {
        adult: false,
        gender: 1,
        id: 12568,
        known_for_department: "Art",
        name: "Barbara Munch",
        original_name: "Barbara Munch",
        popularity: 1.181,
        profile_path: null,
        credit_id: "617c525bd6dbba0066ca441e",
        department: "Art",
        job: "Set Decoration",
      },
      {
        adult: false,
        gender: 0,
        id: 12571,
        known_for_department: "Art",
        name: "Louis Visco",
        original_name: "Louis Visco",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c53c3176a94002c5c9174",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 2,
        id: 12588,
        known_for_department: "Sound",
        name: "Scott Kinzey",
        original_name: "Scott Kinzey",
        popularity: 0.98,
        profile_path: null,
        credit_id: "60f4bb68b84cdd0045b11950",
        department: "Sound",
        job: "Boom Operator",
      },
      {
        adult: false,
        gender: 2,
        id: 12614,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Stephan Dupuis",
        original_name: "Stephan Dupuis",
        popularity: 1.4,
        profile_path: null,
        credit_id: "613d8b802dc9dc0026a359a9",
        department: "Costume \u0026 Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 1,
        id: 24959,
        known_for_department: "Art",
        name: "Maya Shimoguchi",
        original_name: "Maya Shimoguchi",
        popularity: 5.329,
        profile_path: null,
        credit_id: "617c52375aba3200439f19e3",
        department: "Art",
        job: "Supervising Art Director",
      },
      {
        adult: false,
        gender: 0,
        id: 29206,
        known_for_department: "Production",
        name: "Garrett Grant",
        original_name: "Garrett Grant",
        popularity: 1.385,
        profile_path: null,
        credit_id: "613808fef29d6600886183a2",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 29206,
        known_for_department: "Production",
        name: "Garrett Grant",
        original_name: "Garrett Grant",
        popularity: 1.385,
        profile_path: null,
        credit_id: "61eb88e9976e4800daec6c1d",
        department: "Production",
        job: "Unit Production Manager",
      },
      {
        adult: false,
        gender: 0,
        id: 36402,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Heike Merker",
        original_name: "Heike Merker",
        popularity: 4.731,
        profile_path: null,
        credit_id: "617c51850d5d850065f9fba6",
        department: "Costume \u0026 Make-Up",
        job: "Makeup Designer",
      },
      {
        adult: false,
        gender: 1,
        id: 51922,
        known_for_department: "Production",
        name: "Carmen Cuba",
        original_name: "Carmen Cuba",
        popularity: 5.89,
        profile_path: "/c6zX0b29FimnAQ6nkisWxYsCHvE.jpg",
        credit_id: "61eb879e976e48011fb4e388",
        department: "Production",
        job: "Casting",
      },
      {
        adult: false,
        gender: 2,
        id: 54963,
        known_for_department: "Sound",
        name: "Lars Ginzel",
        original_name: "Lars Ginzel",
        popularity: 1.378,
        profile_path: null,
        credit_id: "617c542b38765100631630f9",
        department: "Sound",
        job: "Sound Re-Recording Mixer",
      },
      {
        adult: false,
        gender: 2,
        id: 55081,
        known_for_department: "Crew",
        name: "Jonathan Eusebio",
        original_name: "Jonathan Eusebio",
        popularity: 6.301,
        profile_path: "/9PLs7wy3rLSCY1QNqfkzV4LTZho.jpg",
        credit_id: "61c9fce466a0d30041d24054",
        department: "Crew",
        job: "Stunt Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 59533,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Lindsay Pugh",
        original_name: "Lindsay Pugh",
        popularity: 2.285,
        profile_path: null,
        credit_id: "5da6368347721500135e24c2",
        department: "Costume \u0026 Make-Up",
        job: "Costume Design",
      },
      {
        adult: false,
        gender: 2,
        id: 64564,
        known_for_department: "Acting",
        name: "Mike Möller",
        original_name: "Mike Möller",
        popularity: 4.695,
        profile_path: "/rlWf7aBsTK9g09hH0JQGtn2NXWY.jpg",
        credit_id: "61c9fc81ce9e91001d9edd5e",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 83085,
        known_for_department: "Sound",
        name: "Albert Gasser",
        original_name: "Albert Gasser",
        popularity: 1.198,
        profile_path: null,
        credit_id: "60f4bb5b66a0d3002f7fd99b",
        department: "Sound",
        job: "Sound Effects Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 106743,
        known_for_department: "Acting",
        name: "Eric Brown",
        original_name: "Eric Brown",
        popularity: 17.827,
        profile_path: "/i8tXZoUl5KIiL4My87ipWrgxwTm.jpg",
        credit_id: "61c9fcbb511d090043d7f697",
        department: "Crew",
        job: "Fight Choreographer",
      },
      {
        adult: false,
        gender: 0,
        id: 124697,
        known_for_department: "Sound",
        name: "Markus Stemler",
        original_name: "Markus Stemler",
        popularity: 2.266,
        profile_path: null,
        credit_id: "617c54665294e7002a4a80ed",
        department: "Sound",
        job: "Sound Effects Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 142157,
        known_for_department: "Crew",
        name: "Doug Coleman",
        original_name: "Doug Coleman",
        popularity: 2.396,
        profile_path: "/temeKPrQ9VosJXwb51O3EWxQ5yO.jpg",
        credit_id: "61c9fcc68813e40054c14081",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 2,
        id: 186573,
        known_for_department: "Crew",
        name: "Zack Duhame",
        original_name: "Zack Duhame",
        popularity: 2.321,
        profile_path: "/mI6sdZQaeHDi3jXinS4g1jizywk.jpg",
        credit_id: "61c9fcd16818880063bc42a5",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 2,
        id: 937975,
        known_for_department: "Visual Effects",
        name: "Pierre Buffin",
        original_name: "Pierre Buffin",
        popularity: 5.946,
        profile_path: "/s68NESVKj8jC3m3WVxapCt3a9hF.jpg",
        credit_id: "617c54e471f095008b887fad",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 1,
        id: 958684,
        known_for_department: "Art",
        name: "Nanci Noblett",
        original_name: "Nanci Noblett",
        popularity: 0.98,
        profile_path: null,
        credit_id: "617c52100d5d85002afa4d97",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 1089142,
        known_for_department: "Production",
        name: "Christoph Fisser",
        original_name: "Christoph Fisser",
        popularity: 1.314,
        profile_path: "/7URHtynBXlFSJph8a3ZxqPmrL2k.jpg",
        credit_id: "61eb89d3cedac4001caa6799",
        department: "Production",
        job: "Co-Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 1111715,
        known_for_department: "Writing",
        name: "David Mitchell",
        original_name: "David Mitchell",
        popularity: 2.744,
        profile_path: "/gv5LefiZgvVqCptniPudTcblcol.jpg",
        credit_id: "61eb8653713ea60093ea086f",
        department: "Writing",
        job: "Writer",
      },
      {
        adult: false,
        gender: 2,
        id: 1125755,
        known_for_department: "Visual Effects",
        name: "Ankur Mishra",
        original_name: "Ankur Mishra",
        popularity: 0.6,
        profile_path: null,
        credit_id: "60f4bc1753866e007389b903",
        department: "Visual Effects",
        job: "Visual Effects",
      },
      {
        adult: false,
        gender: 0,
        id: 1153038,
        known_for_department: "Art",
        name: "Wolfgang Metschan",
        original_name: "Wolfgang Metschan",
        popularity: 1.4,
        profile_path: null,
        credit_id: "617c51f784f2490063ab0dc9",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 1209419,
        known_for_department: "Crew",
        name: "Tim Rigby",
        original_name: "Tim Rigby",
        popularity: 2.445,
        profile_path: "/5ckhBJzA3MNxGPDSWytTKrdm26M.jpg",
        credit_id: "61c9fc0ab042280041b103de",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 1324481,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Stephen M. Kelley",
        original_name: "Stephen M. Kelley",
        popularity: 0.676,
        profile_path: null,
        credit_id: "613d8bad60c7510062db6829",
        department: "Costume \u0026 Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 1335860,
        known_for_department: "Art",
        name: "Tarnia Nicol",
        original_name: "Tarnia Nicol",
        popularity: 1.788,
        profile_path: null,
        credit_id: "617c52053e2ec80043b666d3",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 1,
        id: 1338967,
        known_for_department: "Art",
        name: "Esther Schreiner",
        original_name: "Esther Schreiner",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c521bbe2d490045be3e68",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 1341786,
        known_for_department: "Sound",
        name: "Bryan O. Watkins",
        original_name: "Bryan O. Watkins",
        popularity: 1.4,
        profile_path: "/fapThJOs1Xq7y7xYJKp930ZPfog.jpg",
        credit_id: "617c540a176a94002c5c91f5",
        department: "Sound",
        job: "Sound Effects Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 1346937,
        known_for_department: "Art",
        name: "Serban Rotariu",
        original_name: "Serban Rotariu",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c531e0d5d8500916d7655",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 1354916,
        known_for_department: "Art",
        name: "Ravi Bansal",
        original_name: "Ravi Bansal",
        popularity: 1.312,
        profile_path: null,
        credit_id: "617c51e33876510063162bd4",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 0,
        id: 1379940,
        known_for_department: "Acting",
        name: "Joel Adrian",
        original_name: "Joel Adrian",
        popularity: 2.878,
        profile_path: null,
        credit_id: "61c9fd0e6f53e100620807aa",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 1387212,
        known_for_department: "Art",
        name: "Richard Bloom",
        original_name: "Richard Bloom",
        popularity: 0.735,
        profile_path: null,
        credit_id: "617c51d9cb6db5008d44e971",
        department: "Art",
        job: "Art Direction",
      },
      {
        adult: false,
        gender: 2,
        id: 1406839,
        known_for_department: "Crew",
        name: "Scott Rogers",
        original_name: "Scott Rogers",
        popularity: 3.769,
        profile_path: "/dAjaYxCrdUDgrW01piJmseqPhGi.jpg",
        credit_id: "61c9fc23681888001d150b57",
        department: "Crew",
        job: "Stunt Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 1423275,
        known_for_department: "Art",
        name: "Stefanie Übelhör",
        original_name: "Stefanie Übelhör",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c53dc229ae200900ebb64",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 1429235,
        known_for_department: "Visual Effects",
        name: "Pete Polyakov",
        original_name: "Pete Polyakov",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c57f45aba32006278863f",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1432599,
        known_for_department: "Sound",
        name: "Matthew W. Kielkopf",
        original_name: "Matthew W. Kielkopf",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c543971f0950029175036",
        department: "Sound",
        job: "Sound Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 1432599,
        known_for_department: "Sound",
        name: "Matthew W. Kielkopf",
        original_name: "Matthew W. Kielkopf",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c544e3e2ec8008d102a86",
        department: "Sound",
        job: "First Assistant Sound Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 1433199,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Daniel Parker",
        original_name: "Daniel Parker",
        popularity: 1.115,
        profile_path: null,
        credit_id: "617c517a678259008fd9689f",
        department: "Costume \u0026 Make-Up",
        job: "Makeup Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 1434647,
        known_for_department: "Editing",
        name: "Joseph Jett Sally",
        original_name: "Joseph Jett Sally",
        popularity: 0.658,
        profile_path: null,
        credit_id: "60d0cf9c957e6d00730f9775",
        department: "Editing",
        job: "Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 1459898,
        known_for_department: "Visual Effects",
        name: "Moriah Etherington-Sparks",
        original_name: "Moriah Etherington-Sparks",
        popularity: 0.84,
        profile_path: null,
        credit_id: "617c555ad236e600433ba811",
        department: "Visual Effects",
        job: "Visual Effects Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1463552,
        known_for_department: "Visual Effects",
        name: "Marco Lee",
        original_name: "Marco Lee",
        popularity: 0.98,
        profile_path: null,
        credit_id: "617c56305294e70092e8d8a4",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 1548640,
        known_for_department: "Visual Effects",
        name: "Dan Glass",
        original_name: "Dan Glass",
        popularity: 1.946,
        profile_path: null,
        credit_id: "5da63614944a570019218e49",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1613268,
        known_for_department: "Art",
        name: "Jens Gaube",
        original_name: "Jens Gaube",
        popularity: 0.968,
        profile_path: null,
        credit_id: "617c52aae93e95008e80f0af",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 0,
        id: 1614064,
        known_for_department: "Sound",
        name: "Barry O'Sullivan",
        original_name: "Barry O'Sullivan",
        popularity: 0.6,
        profile_path: null,
        credit_id: "60f4bb87befb09002f196064",
        department: "Sound",
        job: "Sound Mixer",
      },
      {
        adult: false,
        gender: 0,
        id: 1615145,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Caroline Hill",
        original_name: "Caroline Hill",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c5994d6dbba0091ed061c",
        department: "Costume \u0026 Make-Up",
        job: "Costume Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 1619081,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Javier Arrieta",
        original_name: "Javier Arrieta",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c597971f0950061acfb4b",
        department: "Costume \u0026 Make-Up",
        job: "Costume Supervisor",
      },
      {
        adult: false,
        gender: 2,
        id: 1621370,
        known_for_department: "Writing",
        name: "Aleksandar Hemon",
        original_name: "Aleksandar Hemon",
        popularity: 1.138,
        profile_path: null,
        credit_id: "61eb8664944a57011167e180",
        department: "Writing",
        job: "Writer",
      },
      {
        adult: false,
        gender: 2,
        id: 1634439,
        known_for_department: "Crew",
        name: "Brett Praed",
        original_name: "Brett Praed",
        popularity: 4.671,
        profile_path: "/pz1lgVP2VeMnNJ672TVR83L8Rky.jpg",
        credit_id: "61c9fc8fce9e91001d9edd93",
        department: "Crew",
        job: "Utility Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 1634811,
        known_for_department: "Crew",
        name: "Dave Ardito",
        original_name: "Dave Ardito",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61c9fd05e72fe800417e2795",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 1711895,
        known_for_department: "Acting",
        name: "Can Aydin",
        original_name: "Can Aydin",
        popularity: 2.792,
        profile_path: "/ayE3dQbjISEgTvYV7xmysjwnw02.jpg",
        credit_id: "61c9fd2c0102c90096f910a3",
        department: "Crew",
        job: "Stunt Double",
      },
      {
        adult: false,
        gender: 2,
        id: 1743134,
        known_for_department: "Acting",
        name: "Chris Reid",
        original_name: "Chris Reid",
        popularity: 0.6,
        profile_path: "/fS9rqppxTuG81ekDIzhCzZsC3Iz.jpg",
        credit_id: "61c9fc9ef5f1c5001af5271b",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 2,
        id: 1770563,
        known_for_department: "Crew",
        name: "Billy Buff",
        original_name: "Billy Buff",
        popularity: 0.695,
        profile_path: null,
        credit_id: "61c9fd3e37b3a9004db0a68d",
        department: "Crew",
        job: "Stunt Double",
      },
      {
        adult: false,
        gender: 0,
        id: 1779514,
        known_for_department: "Acting",
        name: "Cale Schultz",
        original_name: "Cale Schultz",
        popularity: 3.516,
        profile_path: "/fjbYJtD0Ci2k7ImRgcKpNBbiruM.jpg",
        credit_id: "61c9fc4cb54002001c1721e8",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 2,
        id: 1824950,
        known_for_department: "Sound",
        name: "Thomas Wallis",
        original_name: "Thomas Wallis",
        popularity: 0.697,
        profile_path: null,
        credit_id: "60f4bb9466a0d3005e55426b",
        department: "Sound",
        job: "Boom Operator",
      },
      {
        adult: false,
        gender: 1,
        id: 1834193,
        known_for_department: "Crew",
        name: "Hannah Spreitzenbarth",
        original_name: "Hannah Spreitzenbarth",
        popularity: 2.175,
        profile_path: null,
        credit_id: "61c9fc4081a7fc009170a281",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 1903936,
        known_for_department: "Visual Effects",
        name: "Javier Meroño",
        original_name: "Javier Meroño",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c56eb5294e70044005e34",
        department: "Visual Effects",
        job: "Visual Effects",
      },
      {
        adult: false,
        gender: 0,
        id: 1909595,
        known_for_department: "Crew",
        name: "Michael Salven",
        original_name: "Michael Salven",
        popularity: 1.29,
        profile_path: null,
        credit_id: "6138091dd64ac20088df8410",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 1909595,
        known_for_department: "Crew",
        name: "Michael Salven",
        original_name: "Michael Salven",
        popularity: 1.29,
        profile_path: null,
        credit_id: "61eb893131644b004529437e",
        department: "Directing",
        job: "First Assistant Director",
      },
      {
        adult: false,
        gender: 0,
        id: 1974579,
        known_for_department: "Visual Effects",
        name: "Annabelle Zoellin",
        original_name: "Annabelle Zoellin",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c59293f7e1d0042cf5372",
        department: "Visual Effects",
        job: "Visual Effects Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 2012729,
        known_for_department: "Acting",
        name: "Cort Rogers",
        original_name: "Cort Rogers",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61c9fc14511d090063dd308d",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 2040922,
        known_for_department: "Visual Effects",
        name: "Owen McGonigle",
        original_name: "Owen McGonigle",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c569b229ae200649f23cd",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2090951,
        known_for_department: "Art",
        name: "Christian Hoobyar",
        original_name: "Christian Hoobyar",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c52cea097dc0092218fda",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 0,
        id: 2114334,
        known_for_department: "Art",
        name: "Steve Skroce",
        original_name: "Steve Skroce",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5d5c705ec4904800147c955a",
        department: "Art",
        job: "Storyboard Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2133556,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Marta Camer",
        original_name: "Marta Camer",
        popularity: 0.6,
        profile_path: null,
        credit_id: "613d8b6b9979d2006753991d",
        department: "Costume \u0026 Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2138763,
        known_for_department: "Visual Effects",
        name: "Kazia Roach",
        original_name: "Kazia Roach",
        popularity: 0.84,
        profile_path: null,
        credit_id: "617c582c3876510044a1278b",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2138771,
        known_for_department: "Crew",
        name: "Tyson Donnelly",
        original_name: "Tyson Donnelly",
        popularity: 0.84,
        profile_path: null,
        credit_id: "617c5534d388ae0043ec962a",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 0,
        id: 2142877,
        known_for_department: "Acting",
        name: "Jeff Mosley",
        original_name: "Jeff Mosley",
        popularity: 0.631,
        profile_path: "/36rg5YDifingUVlfOrEjtzmBHKX.jpg",
        credit_id: "61c9fc69b0422800902bd889",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 2150906,
        known_for_department: "Visual Effects",
        name: "Balthazar Sahel",
        original_name: "Balthazar Sahel",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c5844fdc4fa00421151e8",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2167320,
        known_for_department: "Production",
        name: "Matt Bilski",
        original_name: "Matt Bilski",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61eb89f75f622b00e26684e8",
        department: "Production",
        job: "Associate Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 2202169,
        known_for_department: "Art",
        name: "Ines Kramer",
        original_name: "Ines Kramer",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c52f1cb6db50042afc74f",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 2374992,
        known_for_department: "Directing",
        name: "Kim Whittaker",
        original_name: "Kim Whittaker",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61eb894f848eb900445c4917",
        department: "Directing",
        job: "Second Assistant Director",
      },
      {
        adult: false,
        gender: 0,
        id: 2392001,
        known_for_department: "Art",
        name: "Geof Darrow",
        original_name: "Geof Darrow",
        popularity: 0.6,
        profile_path: null,
        credit_id: "5d5c7082a3d02700160ac7a6",
        department: "Art",
        job: "Conceptual Design",
      },
      {
        adult: false,
        gender: 0,
        id: 2519511,
        known_for_department: "Acting",
        name: "Gene Pritsker",
        original_name: "Gene Pritsker",
        popularity: 0.652,
        profile_path: null,
        credit_id: "61d7db66511d0900424efebf",
        department: "Sound",
        job: "Orchestrator",
      },
      {
        adult: false,
        gender: 0,
        id: 2583980,
        known_for_department: "Art",
        name: "Chris Cortner",
        original_name: "Chris Cortner",
        popularity: 1.4,
        profile_path: null,
        credit_id: "617c527bd236e600433ba2aa",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 2632928,
        known_for_department: "Production",
        name: "Jesse Ehrman",
        original_name: "Jesse Ehrman",
        popularity: 1.048,
        profile_path: null,
        credit_id: "613809306e0d72008c80374a",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 2641109,
        known_for_department: "Directing",
        name: "Toby Pease",
        original_name: "Toby Pease",
        popularity: 0.828,
        profile_path: null,
        credit_id: "61eb88f6df294515b834f0d4",
        department: "Production",
        job: "Unit Production Manager",
      },
      {
        adult: false,
        gender: 0,
        id: 2674672,
        known_for_department: "Crew",
        name: "Raffael Armbruster",
        original_name: "Raffael Armbruster",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61c9fd1e66a0d30041d24085",
        department: "Crew",
        job: "Stunt Double",
      },
      {
        adult: false,
        gender: 0,
        id: 2674673,
        known_for_department: "Crew",
        name: "Felix Audu",
        original_name: "Felix Audu",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61c9fcf666a0d30041d2406b",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 2681034,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Jalil Romo Corro",
        original_name: "Jalil Romo Corro",
        popularity: 0.98,
        profile_path: null,
        credit_id: "613d8bcfefca000044ed4e14",
        department: "Costume \u0026 Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 2751301,
        known_for_department: "Art",
        name: "Celina Hollaender",
        original_name: "Celina Hollaender",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c52c4fdc4fa002aa56d8b",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 2784705,
        known_for_department: "Directing",
        name: "Michael Saunders",
        original_name: "Michael Saunders",
        popularity: 0.98,
        profile_path: null,
        credit_id: "61eb894131644b00452943ad",
        department: "Directing",
        job: "Second Assistant Director",
      },
      {
        adult: false,
        gender: 0,
        id: 2789138,
        known_for_department: "Visual Effects",
        name: "Aharon Bourland",
        original_name: "Aharon Bourland",
        popularity: 1.403,
        profile_path: null,
        credit_id: "60f4bbc653866e005dbae741",
        department: "Visual Effects",
        job: "Visual Effects Supervisor",
      },
      {
        adult: false,
        gender: 2,
        id: 2808013,
        known_for_department: "Visual Effects",
        name: "Reetu Aggarwal",
        original_name: "Reetu Aggarwal",
        popularity: 2.604,
        profile_path: null,
        credit_id: "60f4bba6da9ef2005ec4c0ef",
        department: "Visual Effects",
        job: "Visual Effects",
      },
      {
        adult: false,
        gender: 0,
        id: 2954692,
        known_for_department: "Production",
        name: "Marc-André Gerke",
        original_name: "Marc-André Gerke",
        popularity: 0.6,
        profile_path: null,
        credit_id: "6011a12aa31440003e28e882",
        department: "Production",
        job: "Location Coordinator",
      },
      {
        adult: false,
        gender: 0,
        id: 3021927,
        known_for_department: "Art",
        name: "Wilko Drews",
        original_name: "Wilko Drews",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c528fcb6db50042afc687",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 1,
        id: 3076434,
        known_for_department: "Art",
        name: "Mariana Vasconcellos",
        original_name: "Mariana Vasconcellos",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c5385d6dbba0091ecf9a3",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 3169987,
        known_for_department: "Visual Effects",
        name: "Daniel Hazeltine",
        original_name: "Daniel Hazeltine",
        popularity: 0.702,
        profile_path: null,
        credit_id: "617c5598a097dc0065fbc3cb",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 3169988,
        known_for_department: "Visual Effects",
        name: "Jamie Hearing",
        original_name: "Jamie Hearing",
        popularity: 0.98,
        profile_path: null,
        credit_id: "6178d39bc2b9df0042a89633",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 2,
        id: 3186542,
        known_for_department: "Crew",
        name: "Gabriel Rios",
        original_name: "Gabriel Rios",
        popularity: 0.98,
        profile_path: "/ecOn9Quf6JLjsTi1vQ21MDXcu2W.jpg",
        credit_id: "61c9fbfe647654008fd618f4",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 3231466,
        known_for_department: "Costume \u0026 Make-Up",
        name: "Aisha King",
        original_name: "Aisha King",
        popularity: 0.6,
        profile_path: null,
        credit_id: "613d8bbac68b690044acdc86",
        department: "Costume \u0026 Make-Up",
        job: "Makeup Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 3277761,
        known_for_department: "Art",
        name: "Robin Plöger",
        original_name: "Robin Plöger",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c53093f7e1d002c3ea381",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 2,
        id: 3289566,
        known_for_department: "Visual Effects",
        name: "Alexander T.H. Browne",
        original_name: "Alexander T.H. Browne",
        popularity: 1.4,
        profile_path: null,
        credit_id: "617c4e36d6dbba0091ecf096",
        department: "Visual Effects",
        job: "VFX Artist",
      },
      {
        adult: false,
        gender: 0,
        id: 3289588,
        known_for_department: "Art",
        name: "Claudia Granucci",
        original_name: "Claudia Granucci",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c52b8d6dbba0091ecf85b",
        department: "Art",
        job: "Set Designer",
      },
      {
        adult: false,
        gender: 0,
        id: 3289590,
        known_for_department: "Art",
        name: "Loren Hoselton",
        original_name: "Loren Hoselton",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c52d9d388ae0043ec9270",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 0,
        id: 3289593,
        known_for_department: "Art",
        name: "Michael Thede",
        original_name: "Michael Thede",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c53303876510063162f1a",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 0,
        id: 3289598,
        known_for_department: "Art",
        name: "Paul Wingert",
        original_name: "Paul Wingert",
        popularity: 0.6,
        profile_path: null,
        credit_id: "617c53d13e2ec80043b66a13",
        department: "Art",
        job: "Set Dresser",
      },
      {
        adult: false,
        gender: 0,
        id: 3360378,
        known_for_department: "Crew",
        name: "Zachary Rogers",
        original_name: "Zachary Rogers",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61c9fc346743fa008750ad6c",
        department: "Crew",
        job: "Utility Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 3360379,
        known_for_department: "Crew",
        name: "Ming Qui",
        original_name: "Ming Qui",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61c9fc5dce9e9100624e91a4",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 3360380,
        known_for_department: "Crew",
        name: "Mustafa Beyter",
        original_name: "Mustafa Beyter",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61c9fcb1511d09008e1f79ab",
        department: "Crew",
        job: "Stunts",
      },
      {
        adult: false,
        gender: 0,
        id: 3372380,
        known_for_department: "Sound",
        name: "Gabriel Isaac Mounsey",
        original_name: "Gabriel Isaac Mounsey",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d7daf0160e73009aa475c3",
        department: "Sound",
        job: "Music Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 3372381,
        known_for_department: "Crew",
        name: "Gabriel Isaac Mounsey",
        original_name: "Gabriel Isaac Mounsey",
        popularity: 0.84,
        profile_path: null,
        credit_id: "61d7dafba589020042c07022",
        department: "Crew",
        job: "Score Engineer",
      },
      {
        adult: false,
        gender: 0,
        id: 3372383,
        known_for_department: "Sound",
        name: "Hans Hafner",
        original_name: "Hans Hafner",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d7db19511d0900424efe42",
        department: "Sound",
        job: "Music Editor",
      },
      {
        adult: false,
        gender: 0,
        id: 3372387,
        known_for_department: "Sound",
        name: "Justin Bell",
        original_name: "Justin Bell",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61d7dbb1c39266001963fd10",
        department: "Sound",
        job: "Orchestrator",
      },
      {
        adult: false,
        gender: 1,
        id: 3392595,
        known_for_department: "Production",
        name: "Karin Wachowski",
        original_name: "Karin Wachowski",
        popularity: 1.614,
        profile_path: null,
        credit_id: "61eb86bdcedac400434fc68e",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 0,
        id: 3392601,
        known_for_department: "Production",
        name: "Aimee Allegretti",
        original_name: "Aimee Allegretti",
        popularity: 1.619,
        profile_path: null,
        credit_id: "61eb8978976e48009e007245",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 3392603,
        known_for_department: "Production",
        name: "Loranne Turgeon",
        original_name: "Loranne Turgeon",
        popularity: 0.6,
        profile_path: null,
        credit_id: "61eb8a11cd204600e57493a3",
        department: "Production",
        job: "Associate Producer",
      },
    ],
    videos: [
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "The Cast Explains The Matrix",
        key: "OZF7aFzcK4I",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2021-12-24T18:00:16.000Z",
        id: "61c700d566a0d3001cac18fe",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: '"Back To Life"',
        key: "aH6ZzDZglS4",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2021-12-18T02:20:16.000Z",
        id: "61bd618f873f00005f687ce9",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "The Game Awards Clip",
        key: "GlDr6aKBtFg",
        site: "YouTube",
        size: 1080,
        type: "Clip",
        official: true,
        published_at: "2021-12-10T04:01:19.000Z",
        id: "61b2f07d65686e001c35ebab",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer 2",
        key: "nNpvWBuTfrc",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2021-12-06T17:00:29.000Z",
        id: "61ae8487f8aee8001a94e098",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: '"Déjà Vu"',
        key: "IgYs_NDyaLs",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2021-12-01T17:00:09.000Z",
        id: "61a8dda60486380029843221",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "The Matrix Legacy",
        key: "0BZUMD85S7s",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
        official: true,
        published_at: "2021-10-07T16:03:22.000Z",
        id: "616d3cf5f92532001d31a206",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Official Trailer 1",
        key: "9ix7TUGVYIo",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
        official: true,
        published_at: "2021-09-09T12:58:11.000Z",
        id: "61383821d64ac2006251a095",
      },
      {
        iso_639_1: "en",
        iso_3166_1: "US",
        name: "Trailer Teaser",
        key: "wdskyfJtyt8",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
        official: true,
        published_at: "2021-09-07T16:00:06.000Z",
        id: "61379432da9ef2002bd3e45d",
      },
    ],
    similarMovies: [
      {
        adult: false,
        backdrop_path: "/nnMXaofDjdWszZ7rbN9hKwK2PNg.jpg",
        genre_ids: [16, 10751, 12, 35],
        id: 7484,
        title: "Open Season",
        original_language: "en",
        original_title: "Open Season",
        overview:
          "Boog, a domesticated 900lb. Grizzly bear finds himself stranded in the woods 3 days before Open Season. Forced to rely on Elliot, a fast-talking mule deer, the two form an unlikely friendship and must quickly rally other forest animals if they are to form a rag-tag army against the hunters.",
        popularity: 26.069,
        poster_path: "/w5Lctmkc1yah215Luxmci4djaiW.jpg",
        release_date: "2006-09-29",
        video: false,
        vote_average: 6.138,
        vote_count: 2132,
      },
      {
        adult: false,
        backdrop_path: "/kAhjS7czQu0gtMVwDqfSBR2KjTF.jpg",
        genre_ids: [12, 14, 28],
        id: 9610,
        title: "Conan the Destroyer",
        original_language: "en",
        original_title: "Conan the Destroyer",
        overview:
          "Conan is commissioned by the evil queen Taramis to safely escort a teen princess and her powerful bodyguard to a far away castle to retrieve the magic Horn of Dagoth. Unknown to Conan, the queen plans to sacrifice the princess when she returns and inherit her kingdom after the bodyguard kills Conan. The queen's plans fail to take into consideration Conan's strength and cunning and the abilities of his sidekicks: the eccentric wizard Akiro, the warrior woman Zula, and the inept Malak. Together the hero and his allies must defeat both mortal and supernatural foes in this voyage to sword-and-sorcery land.",
        popularity: 22.433,
        poster_path: "/tYtWSH9mq6YoIOAyZtluHnzbPvE.jpg",
        release_date: "1984-06-29",
        video: false,
        vote_average: 6.106,
        vote_count: 1119,
      },
      {
        adult: false,
        backdrop_path: "/pnwC8yR4ePfHbLAuo58gbuTnsx9.jpg",
        genre_ids: [35, 10751, 12],
        id: 9641,
        title: "Cheaper by the Dozen 2",
        original_language: "en",
        original_title: "Cheaper by the Dozen 2",
        overview:
          "Steve Martin and Bonnie Hunt return as heads of the Baker family who, while on vacation, find themselves in competition with a rival family of eight children, headed by Eugene Levy,",
        popularity: 21.694,
        poster_path: "/wD68dEtcKuboxd8bhbqiTTxn6cX.jpg",
        release_date: "2005-12-21",
        video: false,
        vote_average: 6.125,
        vote_count: 1670,
      },
      {
        adult: false,
        backdrop_path: "/yBdtVoQe010z8PRJBPaun0iCKso.jpg",
        genre_ids: [10751, 16, 35, 12],
        id: 9642,
        title: "Asterix and the Vikings",
        original_language: "fr",
        original_title: "Astérix et les Vikings",
        overview:
          "Asterix and Obelix have been given a tough mission: Transform the chief's lazy nephew Justforkix into a warrior. When the Vikings abduct him and bring him back to their homeland, Asterix and Obelix must travel to Norway to rescue Justforkix.",
        popularity: 18.351,
        poster_path: "/fer4QcdkxKpVVaZhwKaaS9dmLh9.jpg",
        release_date: "2006-04-05",
        video: false,
        vote_average: 6.11,
        vote_count: 546,
      },
      {
        adult: false,
        backdrop_path: "/80WondpnnRW14urqgt2ptxINvh9.jpg",
        genre_ids: [12, 14, 28, 878],
        id: 9651,
        title: "Supergirl",
        original_language: "en",
        original_title: "Supergirl",
        overview:
          "After losing a powerful orb, Kara, Superman's cousin, comes to Earth to retrieve it and instead finds herself up against a wicked witch.",
        popularity: 23.116,
        poster_path: "/6OfuKKCPFclHOj4SSRRpLzF1lfP.jpg",
        release_date: "1984-07-01",
        video: false,
        vote_average: 5.517,
        vote_count: 439,
      },
      {
        adult: false,
        backdrop_path: "/s9v1QZMVhwShQ7415jPhtfqzyjG.jpg",
        genre_ids: [27, 53],
        id: 13510,
        title: "Eden Lake",
        original_language: "en",
        original_title: "Eden Lake",
        overview:
          "Eden Lake is a relentlessly tense and immaculately paced horror-thriller about modern youth gone wild. When a young couple goes to a remote wooded lake for a romantic getaway, their quiet weekend is shattered by an aggressive group of local kids. Rowdiness quickly turns to rage as the teens terrorize the couple in unimaginable ways, and a weekend outing becomes a bloody battle for survival.",
        popularity: 32.377,
        poster_path: "/lotoZbXMJxyoxx4AS48bNMp5BjS.jpg",
        release_date: "2008-09-12",
        video: false,
        vote_average: 6.757,
        vote_count: 1269,
      },
      {
        adult: false,
        backdrop_path: "/5qWtPhMLxY7cS1GkAvJZlPKgNPd.jpg",
        genre_ids: [10751, 16, 35, 14],
        id: 11836,
        title: "The SpongeBob SquarePants Movie",
        original_language: "en",
        original_title: "The SpongeBob SquarePants Movie",
        overview:
          "There's trouble brewing in Bikini Bottom. Someone has stolen King Neptune's crown, and it looks like Mr. Krab, SpongeBob's boss, is the culprit. Though he's just been passed over for the promotion of his dreams, SpongeBob stands by his boss, and along with his best pal Patrick, sets out on a treacherous mission to Shell City to reclaim the crown and save Mr. Krab's life.",
        popularity: 84.138,
        poster_path: "/6sgo6TCakeL4KFwwcJyvkZ7zhMX.jpg",
        release_date: "2004-11-14",
        video: false,
        vote_average: 6.938,
        vote_count: 2205,
      },
      {
        adult: false,
        backdrop_path: "/utozhLLXu9lXuoilMomJfXJOy5x.jpg",
        genre_ids: [18, 12, 14],
        id: 11849,
        title: "Dungeons \u0026 Dragons",
        original_language: "en",
        original_title: "Dungeons \u0026 Dragons",
        overview:
          "The Empire of Izmer is a divided land: elite magicians called “mages” rule while lowly commoners are powerless. When Empress Savina vows to bring equality and prosperity to her land, the evil mage Profion plots to depose her.",
        popularity: 12.664,
        poster_path: "/h5ll8lbgKZoNdfVRUrA37Kgke3n.jpg",
        release_date: "2000-12-08",
        video: false,
        vote_average: 4.267,
        vote_count: 448,
      },
      {
        adult: false,
        backdrop_path: "/pwfULXiGJmjBPZPssnFbHUHB7at.jpg",
        genre_ids: [27, 28, 53],
        id: 11880,
        title: "Dog Soldiers",
        original_language: "en",
        original_title: "Dog Soldiers",
        overview:
          "A squad of British soldiers on training in the lonesome Scottish wilderness find a wounded Special Forces captain and the remains of his team. As they encounter zoologist Megan, it turns out that werewolves are active in the region. They have to prepare for some action as the there will be a full moon tonight...",
        popularity: 11.951,
        poster_path: "/cUsSL2x0HYS7QmTwPcEE66b52Wt.jpg",
        release_date: "2002-05-10",
        video: false,
        vote_average: 6.7,
        vote_count: 612,
      },
      {
        adult: false,
        backdrop_path: "/oegA1YBl1PszRbB0qj4UpVSr9Jt.jpg",
        genre_ids: [16, 10751],
        id: 11886,
        title: "Robin Hood",
        original_language: "en",
        original_title: "Robin Hood",
        overview:
          "With King Richard off to the Crusades, Prince John and his slithering minion, Sir Hiss, set about taxing Nottingham's citizens with support from the corrupt sheriff - and staunch opposition by the wily Robin Hood and his band of merry men.",
        popularity: 50.416,
        poster_path: "/x9AvkYek0bGdxQSZ8W3lAjGrREm.jpg",
        release_date: "1973-11-08",
        video: false,
        vote_average: 7.277,
        vote_count: 3565,
      },
      {
        adult: false,
        backdrop_path: "/spyZFUG0lR6FEbvMn3YBcxT8vdx.jpg",
        genre_ids: [35, 10749, 18, 10751, 10402],
        id: 11887,
        title: "High School Musical 3: Senior Year",
        original_language: "en",
        original_title: "High School Musical 3: Senior Year",
        overview:
          "It's almost graduation day for high school seniors Troy, Gabriella, Sharpay, Chad, Ryan and Taylor — and the thought of heading off in separate directions after leaving East High has these Wildcats thinking they need to do something they'll remember forever. Together with the rest of the Wildcats, they stage a spring musical reflecting their hopes and fears about the future and their unforgettable experiences growing up together. Will their final show break them apart or bring them together for the greatest moment in Wildcat history?",
        popularity: 28.93,
        poster_path: "/cKWIxQh2dMUgjsxJenrf7A81D95.jpg",
        release_date: "2008-10-11",
        video: false,
        vote_average: 6.589,
        vote_count: 3026,
      },
      {
        adult: false,
        backdrop_path: "/VtFa6Ph0xCO6QJ86ihCrpsDBIO.jpg",
        genre_ids: [35, 10751, 10749, 14],
        id: 10808,
        title: "Dr. Dolittle 2",
        original_language: "en",
        original_title: "Dr. Dolittle 2",
        overview:
          "A group of beavers ask Dr. Dolittle to save their habitat from loggers. The only hope is to get the forest preserved because it's the home of a protected bear, but there's a problem: the bear's the only bear in the forest, so she can't reproduce. Undaunted, Dolittle persuades a circus bear to help out, but he has to teach him not just the ways of the wild, but the wiles of lady bears too.",
        popularity: 19.792,
        poster_path: "/qEzgdEPLDJBPUj47sobRKzmuETc.jpg",
        release_date: "2001-06-22",
        video: false,
        vote_average: 5.275,
        vote_count: 1339,
      },
      {
        adult: false,
        backdrop_path: "/fYr0fqT9NImOuaN1QgnDHgGh4Ci.jpg",
        genre_ids: [16, 10751, 12, 878],
        id: 10865,
        title: "Atlantis: The Lost Empire",
        original_language: "en",
        original_title: "Atlantis: The Lost Empire",
        overview:
          "The world's most highly qualified crew of archaeologists and explorers is led by historian Milo Thatch as they board the incredible 1,000-foot submarine Ulysses and head deep into the mysteries of the sea. The underwater expedition takes an unexpected turn when the team's mission must switch from exploring Atlantis to protecting it.",
        popularity: 42.051,
        poster_path: "/8fUEFPUTF7kBMuKPiSQHxPvd8EZ.jpg",
        release_date: "2001-06-02",
        video: false,
        vote_average: 6.944,
        vote_count: 3799,
      },
      {
        adult: false,
        backdrop_path: "/slPsf3cQFt8ffQSQbuOlpYlV84s.jpg",
        genre_ids: [14, 16, 10749, 10751],
        id: 10882,
        title: "Sleeping Beauty",
        original_language: "en",
        original_title: "Sleeping Beauty",
        overview:
          "A beautiful princess born in a faraway kingdom is destined by a terrible curse to prick her finger on the spindle of a spinning wheel and fall into a deep sleep that can only be awakened by true love's first kiss. Determined to protect her, her parents ask three fairies to raise her in hiding. But the evil Maleficent is just as determined to seal the princess's fate.",
        popularity: 72.979,
        poster_path: "/hsQD3U3P8wkU63jgKg9TlK5oxK3.jpg",
        release_date: "1959-02-17",
        video: false,
        vote_average: 6.929,
        vote_count: 4230,
      },
      {
        adult: false,
        backdrop_path: "/ikpwuaK0yzNhXO24OeB7cKulhZE.jpg",
        genre_ids: [16, 10751],
        id: 10895,
        title: "Pinocchio",
        original_language: "en",
        original_title: "Pinocchio",
        overview:
          "Lonely toymaker Geppetto has his wishes answered when the Blue Fairy arrives to bring his wooden puppet Pinocchio to life. Before becoming a real boy, however, Pinocchio must prove he's worthy as he sets off on an adventure with his whistling sidekick and conscience, Jiminy Cricket.",
        popularity: 92.374,
        poster_path: "/ynkEEi296ofs9kCfRWcaWxOWN1n.jpg",
        release_date: "1940-02-23",
        video: false,
        vote_average: 7.081,
        vote_count: 4722,
      },
      {
        adult: false,
        backdrop_path: "/3iF68uCSFWQqCl5eO7ehehR6fu6.jpg",
        genre_ids: [16, 12, 10751, 35],
        id: 10898,
        title: "The Little Mermaid II: Return to the Sea",
        original_language: "en",
        original_title: "The Little Mermaid II: Return to the Sea",
        overview:
          "Set several years after the first film, Ariel and Prince Eric are happily married with a daughter, Melody. In order to protect Melody from the Sea Witch, Morgana, they have not told her about her mermaid heritage. Melody is curious and ventures into the sea, where she meets new friends. But will she become a pawn in Morgana's quest to take control of the ocean from King Triton?",
        popularity: 13.182,
        poster_path: "/tzrrZlY7pVTRV9GXd7Q1BkynnUx.jpg",
        release_date: "2000-01-23",
        video: false,
        vote_average: 6.455,
        vote_count: 1378,
      },
      {
        adult: false,
        backdrop_path: "/qjdInV140rRUqcuEIBUmjylHaZ9.jpg",
        genre_ids: [27, 53],
        id: 9902,
        title: "Wrong Turn",
        original_language: "en",
        original_title: "Wrong Turn",
        overview:
          "Chris crashes into a carload of other young people, and the group of stranded motorists is soon lost in the woods of West Virginia, where they're hunted by three cannibalistic mountain men who are grossly disfigured by generations of inbreeding.",
        popularity: 89.68,
        poster_path: "/ixBGcbQKvl2N4VZmJfmQkyKBJCX.jpg",
        release_date: "2003-05-30",
        video: false,
        vote_average: 6.313,
        vote_count: 1944,
      },
      {
        adult: false,
        backdrop_path: "/8p4gCdDT55PMY3UMDvo6ybzMrai.jpg",
        genre_ids: [16, 35, 10751, 878],
        id: 9928,
        title: "Robots",
        original_language: "en",
        original_title: "Robots",
        overview:
          "Rodney Copperbottom is a young robot inventor who dreams of making the world a better place, until the evil Ratchet takes over Big Weld Industries. Now, Rodney's dreams – and those of his friends – are in danger of becoming obsolete.",
        popularity: 40.911,
        poster_path: "/bS94Dt0FKW1463UQyv78MVOw6Pf.jpg",
        release_date: "2005-03-10",
        video: false,
        vote_average: 6.398,
        vote_count: 3695,
      },
      {
        adult: false,
        backdrop_path: "/5xt0OiDP42CVoFDj8Fmh3CQlo2X.jpg",
        genre_ids: [14, 27],
        id: 9954,
        title: "The Covenant",
        original_language: "en",
        original_title: "The Covenant",
        overview:
          "Four young men who belong to a supernatural legacy are forced to battle a fifth power long thought to have died out. Another great force they must contend with is the jealousy and suspicion that threatens to tear them apart.",
        popularity: 13.837,
        poster_path: "/4jwVlbGt3BeLr8HCbCTVa72IcWe.jpg",
        release_date: "2006-09-08",
        video: false,
        vote_average: 5.475,
        vote_count: 803,
      },
      {
        adult: false,
        backdrop_path: "/h37N1O8LUyGW1o2dIWufm9jzpk7.jpg",
        genre_ids: [16, 10751, 35],
        id: 9982,
        title: "Chicken Little",
        original_language: "en",
        original_title: "Chicken Little",
        overview:
          "When the sky really is falling and sanity has flown the coop, who will rise to save the day? Together with his hysterical band of misfit friends, Chicken Little must hatch a plan to save the planet from alien invasion and prove that the world's biggest hero is a little chicken.",
        popularity: 36.17,
        poster_path: "/1wg65q3daTE8rGfaUhBxLdXk6NL.jpg",
        release_date: "2005-11-04",
        video: false,
        vote_average: 5.886,
        vote_count: 3156,
      },
    ],
  },
});

export const loginState = atom({
  key: "loginState",
  default: false,
});

export const userDBState = atom({
  key: "userDBState",
  default: {
    uid: "",
    username: "",
    movies: undefined,
  },
});

export const uidState = selector({
  key: "uidState",
  get: ({ get }) => {
    return get(userDBState).uid;
  },
});

export const likedMoviesState = selector<IUserDB["movies"]>({
  key: "likedMoviesState",
  get: ({ get }) => {
    return get(userDBState).movies;
  },
});

export const usernameState = selector({
  key: "usernameState",
  get: ({ get }) => {
    return get(userDBState).username;
  },
});

export const userState = atom({
  key: "userState",
  default: {
    thirdParty: false,
    emailVerified: false,
    email: "",
    displayName: "",
    photoURL: "",
  },
});

export const likedState = atom({
  key: "likedState",
  default: false,
});
